### ISSUE TITLE
Crash while opening a full screen game

### ISSUE THREAD

**Issue by alanimgur** [WindowsNT/ScreenCapture#1]
This is an excellent project! It's a really nice and simple library that is exactly what I was looking for. Unfortunately I ran into a problem where as soon as I open a full screen game, the library instantly crashes.

**To reproduce:**
- Open the example project and change 10 seconds to something longer, like 100 seconds.
- Run the example project, ScreenCapture.exe
- Load any full screen game. In my case I opened Apex Legends.
- Once you're in the game, Alt-Tab back to ScreenCapture and see that it's crashed and is no longer recording.

**Comment by WindowsNT** [comment]
I 'll take a look, thanks for the notification.

**Comment by alanimgur** [comment]
Upon further investigation, I believe the problem is specifically with Alt-Tabbing. If I start recording from within the game, using a Hotkey bound to `DesktopCapture`, then the recording proceeds as expected. Then when I Alt-Tab back to the desktop, the recording immediately crashes.

**Comment by WindowsNT** [comment]
It's in the line that calls `AcquireNextFrame`. If this returns DXGI_ERROR_ACCESS_LOST, the interface needs to be recreated - I will work on that.

**Comment by WindowsNT** [comment]
Check the new push

**Comment by alanimgur** [comment]
Yes, thank you! That did indeed fix the problem!

Unfortunately during testing though I've found another issue that I'd like to bring to your attention. I've opened another ticket here: https://github.com/WindowsNT/ScreenCapture/issues/2
