### ISSUE TITLE
out of memory error?

### ISSUE THREAD

**Issue by Boomslangnz** [WindowsNT/ScreenCapture#13]
Hello,

Code is awesome so thanks alot for making it, It works fantastic on my main pc which has stats
-Intel Core i5-12600KF 3.70ghz and 32gb ram with a GTX 2080 Super GPU

however, I have tried on 2 other devices now and both cannot complete a video as after around 15-25 seconds they both give 0x8007000e which I believe is E_OUTOFMEMORY

1 is an older laptop running Windows 10 with i7 cpu 8gb ram and a 960M GPU while the other is a GPD Win 3 device which uses i5 with 16gb ram and Intel Iris XE GPU

I tried running GPU-Z on my Main PC thinking perhaps there was a memory leak somewhere but I saw nothing obvious showing on the stats.

Is there anything I can try here? Ive tried changing bitrate and fps etc but results always the same

Thanks

**Comment by WindowsNT** [comment]
What happens when you capture only a specific area instead of the whole screen?

**Comment by Boomslangnz** [comment]
That is what i am doing actually, capturing window. I did relise afterwards that the laptop was defaulting to using intel gpu instead of the nvidia 960m. However i cant seem to get it to capture on the 960m at all, ive tried using getadapter but setting dp.ad to other adapters never seems to capture on it. It does begin capturing on the default intel gpu if i leave dp.ad = 0 but that is weak gpu

**Comment by WindowsNT** [comment]
There's an option in Control Panel Device settings that allows setting an app to 'high perfornance' graphics in order to use the good cpu.

**Comment by Boomslangnz** [comment]
Yes ive done that, but once i did that then capture doesnt work anymore. Don't i need to change adapter to use the nvidia gpu in capturing code?

**Comment by WindowsNT** [comment]
I 'll take a look,
