### ISSUE TITLE
Streaming as mp4

### ISSUE THREAD

**Issue by Boomslangnz** [WindowsNT/ScreenCapture#18]
Hi

ive found no problem with streaming asf file but how can i stream as mp4 file? It seems asf files only ever start playing from beginning of file so i was hoping to get something which can show live recording effectively

Thanks!

**Comment by WindowsNT** [comment]
I think that mp4 needs finalization as a format. I dont believe it is suitable for streaming.

**Comment by Boomslangnz** [comment]
ok thanks
