### ISSUE TITLE
can i take pictures instead of videos?

### ISSUE THREAD

**Issue by ghost** [WindowsNT/ScreenCapture#6]
I want to use it for a neural network, but the neural network takes snapshots as input and not video if done in real time.

**Comment by WindowsNT** [comment]
Yes, latest update can grab raw frames. Check the demo.

**Comment by ghost** [comment]
And can I do it so that I can choose the format?

**Comment by WindowsNT** [comment]
The data returned from the library is raw RGBA array, for example if your resolution is 1920x1080 you will get a 8294400 byte array. It's up to you how you compress or save it then.

**Comment by ghost** [comment]
@WindowsNT thanks
