### ISSUE TITLE
Recording Audio

### ISSUE THREAD

**Issue by VogelPapaFinn** [WindowsNT/ScreenCapture#9]
How exactly do I record audio? `VISTAMIXERS::EnumVistaMixers()` doesnt exist and I cant understand your instructions. Pls help ^^

**Comment by WindowsNT** [comment]
It's there (EnumVistaMixers) in capture.hpp.
Take a look at https://www.codeproject.com/Articles/5256890/ScreenCapture-Single-header-DirectX-library to see how to record audio.

**Comment by VogelPapaFinn** [comment]
There is no code example. I dont know how to get a vector with the audio device ID. And `VISTAMIXER:EnumVistaMixers()` doesnt exists. There is just `EnumVistaMixers()` that returns nothing (void).

**Comment by VogelPapaFinn** [comment]
I tried it multiple times. I dont know how to do it. Ive got 0 ideas left.

**Comment by VogelPapaFinn** [comment]
Seems like your project is dead, out of date and not supported anymore. You're not answering so I guess I need to use an other library. Insufficient documentation

**Comment by WindowsNT** [comment]
There is an 'audio capture' section in the codeproject article.  I demonstrate how to record it.  
That's the issue with free and open source code, support is not free. 
Good luck.
